language: node_js
node_js:
  - "lts/*"
cache:
  directories:
   - node_modules
install:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "gatsby build --prefix-paths"
deploy:
  provider: pages
  skip_clenaup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

